server:
  port: 8080
spring:
#  application:
#    name: houses-service
  freemarker:
    #设定ftl文件路径
    template-loader-path: classpath:/templates
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存、即时刷新，线上应为true
    cache: false
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
